In [1]:
import numpy as np
import svd

In [2]:
A = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
U, S, V_T = svd.decompose(A)
print("Is SVD correct:", svd.verify(A, U, S, V_T))
print("A:", A)
print("U*S*V_T:", np.dot(U, np.dot(S, V_T)))

Is SVD correct: True
A: [[1 2 3]
 [2 4 6]
 [3 6 9]]
U*S*V_T: [[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]


In [3]:
A = np.random.rand(3, 2)
U, S, V_T = svd.decompose(A)
print("Is SVD correct:", svd.verify(A, U, S, V_T))
print("A:", A.shape)
print("U:", U.shape)
print("S:", S.shape)
print("V_T:", V_T.shape)
print("A:", A)
print("U*S*V_T:", np.dot(U, np.dot(S, V_T)))

Is SVD correct: True
A: (3, 2)
U: (3, 3)
S: (3, 2)
V_T: (2, 2)
A: [[0.47682219 0.09153531]
 [0.28670823 0.93904919]
 [0.5924158  0.96242751]]
U*S*V_T: [[0.47682219 0.09153531]
 [0.28670823 0.93904919]
 [0.5924158  0.96242751]]


In [4]:
A = np.random.rand(2, 3)
U, S, V_T = svd.decompose(A)
print("Is SVD correct:", svd.verify(A, U, S, V_T))
print("A:", A.shape)
print("U:", U.shape)
print("S:", S.shape)
print("V_T:", V_T.shape)
print("V_T:", V_T.shape)
print("A:", A)
print("U*S*V_T:", np.dot(U, np.dot(S, V_T)))

Is SVD correct: True
A: (2, 3)
U: (2, 2)
S: (2, 3)
V_T: (3, 3)
V_T: (3, 3)
A: [[0.10691935 0.33654527 0.61385325]
 [0.72700517 0.14413002 0.21348354]]
U*S*V_T: [[0.10691935 0.33654527 0.61385325]
 [0.72700517 0.14413002 0.21348354]]
