In [6]:
import numpy as np
import svd

In [8]:
A = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
U, S, V_T = svd.svd(A)
print("Is SVD correct:", svd.verify_svd(A, U, S, V_T))
print("A:", A)
print("U*S*V_T:", np.dot(U, np.dot(S, V_T)))

Is SVD correct: True
A: [[1 2 3]
 [2 4 6]
 [3 6 9]]
U*S*V_T: [[0.99999999 1.99999999 3.00000001]
 [1.99999999 3.99999998 6.00000002]
 [2.99999998 5.99999997 9.00000003]]


In [15]:
A = np.random.rand(2, 3)
U, S, V_T = svd.svd(A)
print("Is SVD correct:", svd.verify_svd(A, U, S, V_T))
print("A:", A)
print("\n U:", U)
print("\n S:", S)
print("\n V_T:", V_T)

Is SVD correct: True
A: [[0.40295856 0.22198322 0.32218914]
 [0.49959849 0.30783639 0.53024239]]

 U: [[-0.57793237 -0.81608466  0.95117696]
 [-0.81608466  0.57793237  0.30864607]]

 S: [[9.68227249e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.92695024e-02 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.47621201e-09]]

 V_T: [[-0.66161891 -0.39196567 -0.63923652]
 [-0.67680952 -0.05480877  0.73411503]
 [ 0.32278366 -0.91834575  0.22902358]]
