In [1]:
import numpy as np
import svd

In [2]:
A = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
U, S, V_T = svd.decompose(A)
print("Is SVD correct:", svd.verify(A, U, S, V_T))
print("A:", A)
print("U*S*V_T:", np.dot(U, np.dot(S, V_T)))

Is SVD correct: True
A: [[1 2 3]
 [2 4 6]
 [3 6 9]]
U*S*V_T: [[1.         2.         3.        ]
 [2.         4.00000001 6.        ]
 [2.99999999 6.00000003 8.99999998]]


In [3]:
A = np.random.rand(2, 3)
U, S, V_T = svd.decompose(A)
print("Is SVD correct:", svd.verify(A, U, S, V_T))
print("A:", A.shape)
print("U:", U.shape)
print("S:", S.shape)
print("V_T:", V_T.shape)

Is SVD correct: True
A: (2, 3)
U: (2, 2)
S: (2, 3)
V_T: (3, 3)
U: [[-0.96449087  0.26411621]
 [-0.26411621 -0.96449087]]
S: [[1.64860727 0.         0.        ]
 [0.         0.15615508 0.        ]]
V_T: [[-0.62447749 -0.48729052 -0.61038989]
 [-0.71074108  0.03050476  0.70279199]
 [ 0.32384407 -0.87270695  0.36538692]]
